fix: Replace parameter for pip. -e should be -r
python-microservices/microservices-scaffold pull request #216
Opened 2020-10-11 20:45 UTC by felipem775

2020-10-11 22:27 UTC, avara1986 requested changes

2020-10-11 22:27 UTC, avara1986 commented on requirements-dev.txt
> +black==20.8b1
Add this packages in Pipfile too

2020-10-11 22:27 UTC, avara1986 commented on pyproject.toml
> +[tool.black]
It's ok the `pyproject.toml` but, in the **microservices-scaffold**, this configuration could be placed in `setup.cfg` and this file contains at this moment the configuration of the linters and other libaries, could be better put all the configuration in a single file :+1:

2020-10-11 22:27 UTC, avara1986 commented on .pre-commit-config.yaml
> +        - repo: https://github.com/ambv/black
replace these spaces for [2 paces](https://docs.saltstack.com/en/master/topics/troubleshooting/yaml_idiosyncrasies.html#:~:text=The%20suggested%20syntax%20for%20YAML,uniform%20and%20not%20deeply%20nested.):

*The suggested syntax for YAML files is to use 2 spaces for indentation, but YAML will follow whatever indentation system that the individual file uses. Indentation of two spaces works very well for SLS files given the fact that the data is uniform and not deeply nested.*

2020-10-15 17:44 UTC, avara1986 commented on pyproject.toml
> +[tool.black]
Sorry, my fault, Black not support setup.cfg:

- https://github.com/psf/black/issues/683
- https://github.com/flying-sheep/awesome-python-packaging

2020-10-15 18:04 UTC, avara1986 approved these changes

2020-10-15 20:54 UTC, alexppg commented
What do you thing about adding `pytest-black` to the CI to make sure everybody uses it? https://pypi.org/project/pytest-black/ @avara1986 @felipem775

2020-10-15 21:04 UTC, avara1986 commented
Good idea @alexppg! but we could add this package in these steps:
- Add black with pre-commit
- Update all repository with black's changes
- Add pytest-black to prevent new "errors" of format

What do you say? :) do we create a issue to add this validation? :muscle:

2020-10-15 21:11 UTC, alexppg commented
Nice, done then. https://github.com/python-microservices/microservices-scaffold/issues/218 and https://github.com/python-microservices/microservices-scaffold/issues/219

2020-10-15 21:11 UTC, alexppg approved these changes

2020-10-15 21:11 UTC, merged